url:
  publicHost: http://fol.ztessc.com.cn/public
  baseHost: http://fol.ztessc.com.cn/base
  easHost: http://fol.ztessc.com.cn/eas
  fscHost: http://fol.ztessc.com.cn/fsc
  basHost: http://fol.ztessc.com.cn/bas
  timerHost: http://fol.ztessc.com.cn/ip/timerManage
  invoiceIpoolHost: http://fol.ztessc.com.cn/ipool
  fscAuditList: http://fol.ztessc.com.cn/fsc/auditList
  fscAuditAdjustDirector: http://fol.ztessc.com.cn/fsc/auditAdjustDirector
  fscBillExchange: http://fol.ztessc.com.cn/fsc/billExchange

user:
  account: hc001
  password: LMJT123456
leader:
  account: hc002
  password: LMJT123456
finance:
  account: hc003
  password: zfs123456

Approval:
  approvalGroupC: 自动化财务初审
  approvalUserC: hc3
  approvalGroupF: 自动化财务复审
  approvalUserF: hc3